[server]
host = "0.0.0.0"
port = 8888
[server.auth]
secret = "secret"

[database]
host = "db"
username = "server"
password = "server"
database = "server_monitor"
port = 5432

[redis]
host = "redis"
port = 6379

[superuser]
username = "superuser"
password = "superuser"
email = "stepbashsuperuser@gmail.com"
