version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: server
      POSTGRES_USER: server
      POSTGRES_DB: server_monitor

    ports:
      - "5432:5432"

  redis:
    image: redis:latest

    ports:
      - "6379:6379"

  app:
    build: .
    privileged: true
    pid: host
    volumes:
        - /proc:/host_proc:ro
    ports:
      - "8888:8888"
    depends_on:
      - db
      - redis